var c = 1 // Do - While começa de cima para baixo
do { //do - FAÇA
    console.log(`Passo ${c}`)
    c++
}while(c <= 10)

        /*Use do-while se você precisar que o bloco de código 
        seja executado uma vez antes da condição ser verificada.
         Por exemplo, se você está pedindo ao usuário para inserir um valor 
         e deseja garantir que o pedido seja feito pelo menos uma vez, um do-while seria apropriado.
         */

var c = 1
while (c <= 6) { //while - ENQUANTO
    console.log(`Passo ${c}`)
    c++//c = c + 1 (valor da var + 1)
}

